version: '3.8'
services:
  springboot-app:
    image: api
    build: .
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - mysql_db
  
  mysql_db:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: parkin
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  
